spring:

  application:
    name: ${APPLICATION_NAME:architecture_map}

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/architecture_map?currentSchema=${spring.application.name}}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  elasticsearch:
    uris: https://localhost:9200
    username: ${ELASTIC_USERNAME}
    password: ${ELASTIC_PASSWORD}

  data:
    elasticsearch:
      repositories:
        enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

sendgrid:
  api-key: ${SENDGRID_KEY}
  from-email: ${EMAIL_USERNAME}

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true

jwt:
  key: ${JWT_KEY}
  access-token-expiration: 3600000
