spring:

  application:
    name: ${APPLICATION_NAME:architecture_map}

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/architecture_map?currentSchema=${spring.application.name}}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  elasticsearch:
    uris: http://elastic:9200

  data:
    elasticsearch:
      repositories:
        enabled: true

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
